---
# author: fat

- name: jdbc | Check if java local file is already configured.
  stat: path={{ jdbc_file_path }}
  connection: local
  register: jdbc_file_result

- name: jdbc | Download jdbc file.
  get_url: url={{ jdbc_file_url }} dest={{ software_files_path }}
  connection: local
  when: not jdbc_file_result.stat.exists

- name: jdbc | Unarchive jdbc file.
  unarchive:
    src: "{{ jdbc_file_path }}"
    dest: "{{ software_files_path }}"
    creates: "{{ software_files_path }}/{{ jdbc_jar_file }}"
  connection: local

- name: install | Check if jar path is already configured.
  stat: path={{ remote_jar_path }}
  register: jar_path_result

- name: install | Create jar file path.
  file: path={{ remote_jar_path }} state=directory
  when: not jar_path_result.stat.exists

- name: jdbc | Copy jdbc jar file to agent.
  copy: src={{ software_files_path }}/{{ jdbc_jar_file }} dest={{ remote_jar_path }}/mysql-connector-java.jar
