---
#author: fat
- block:
  - name: 检查ceph集群状态是否正常
    shell: ceph -s
    register: ceph_status

  - name: 展示ceph集群状态信息
    debug:
      var: ceph_status.stdout_lines

  when: inventory_hostname in groups["ceph"]

- pause:
    prompt: "ceph0和ceph1集群状态都ok吗? \n确认ok请按回车继续，否则请按Ctrl+C，然后按a中止!"

- block:
  - name: 检查docker集群状态
    shell: docker ps -a
    register: docker_status
  
  - name: 展示docker的运行信息
    debug:
      var: docker_status.stdout_lines
  
  when: inventory_hostname in groups["openstack"]

- pause:
    prompt: "docker运行状态都ok吗? \n确认ok请按回车继续，否则请按Ctrl+C，然后按a中止!"

- name: 在ceph0挂载cephfs
  shell: "mount -t ceph xxxxx"
  when: inventory_hostname == "ceph-test-1"
 

- name: 在ceph1挂载cephfs
  shell: | 
         mount -t ceph xxxxx 
         mount -t ceph xxxxx
  when: inventory_hostname == "ceph-test-2"
 

- name: 在ceph3挂载cephfs
  shell: "mount -t ceph xxxxx"
  when: inventory_hostname == "ceph-test-3"
 

- block:  
  - name: 检查nextcloud容器的cephfs挂载情况
    shell: "docker exec -i nextcloud_1 df -h |egrep \"192.*nextcloud.*data\""
    register: mount_nc
    ignore_errors: true
   
  - name: 如果没有mount cephfs，执行mount -a挂载
    shell: "docker exec -i nextcloud_1 mount -a"
    when: mount_nc.stdout == ""

  when: inventory_hostname in groups["ceph"]


- block:
  - name: 输出grastate.dat文件
    shell: more /var/lib/docker/volumes/mariadb/_data/grastate.dat
    register: grastate
  
  - name: 展示mariadb-galera集群节点grastate信息，确认seqno
    debug:
      var: grastate
  
  - name: 更换openstack的界面logo
    shell: |
           docker cp /home/openstack/logo/favicon.ico horizon:/var/lib/kolla/venv/lib/python2.7/site-packages/static/dashboard/img/
           docker cp /home/openstack/logo/logo.svg horizon:/var/lib/kolla/venv/lib/python2.7/site-packages/static/dashboard/img/
           docker cp /home/openstack/logo/logo-splash.svg horizon:/var/lib/kolla/venv/lib/python2.7/site-packages/static/dashboard/img/
  when: inventory_hostname == "openstack-test" or inventory_hostname == "ceph-test-3"

- name: 使用kolla-ansible完成mariadb集群恢复,具体情况请去{{ inventory_hostname }}主机tail日志{{ mariadb_recovery_log }}
  shell: kolla-ansible -i /root/multinode mariadb_recovery -vvv > {{ mariadb_recovery_log }}
  register: recover_answer
  until: recover_answer.rc == 0
  retries: 2
  delay: 10
  when: inventory_hostname == "openstack-test"

